package forms;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import mainClasses.AdminStaff;
import mainClasses.Staff;
import mainClasses.TransportSystem;
import mainClasses.Vehicle;
import utilities.ISubject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shivers
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.getRootPane().setDefaultButton(btnLogin);
        loadData();
    }

    private void loadData() {
        TransportSystem.getInstance();
        /*JFileChooser objFileDialog = new JFileChooser();
        
        objFileDialog.setCurrentDirectory(new File("."));
        Create Dialogue result with default cancel action
        int intDialogResult = JFileChooser.CANCEL_OPTION;
        Show Dialog
        intDialogResult = objFileDialog.showOpenDialog(this);
        if (intDialogResult == JFileChooser.APPROVE_OPTION) { //Removed choosing the location of the file for now
            
            File objFile = objFileDialog.getSelectedFile();
            JOptionPane.showMessageDialog(this, objFile.getPath()); */
        File objFile = new File("System");
        if (objFile.exists() && objFile.canRead()) {

            try (ObjectInputStream objIn = new ObjectInputStream(
                    new BufferedInputStream(
                            new FileInputStream(objFile)))) {
                Object objData = objIn.readObject();
                TransportSystem.setTransportSystem((TransportSystem) objData);

            } catch (ClassNotFoundException | IOException | ClassCastException ex) {
                JOptionPane.showMessageDialog(this,
                        "Data file could not be read" + ex,
                        "Operation aborted", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "File not found / unreadable.",
                    "Error accessing file", JOptionPane.ERROR_MESSAGE);
        }
        /*} else {
            JOptionPane.showMessageDialog(this,
                    "File load cancelled",
                    "Operation aborted", JOptionPane.INFORMATION_MESSAGE);
        }*/
    }

    private void findAdmin() {
        String adminID = txtAdminID.getText();
        ArrayList<Staff> staffList = TransportSystem.getInstance().getStaffList();

        for (Staff currentStaff : staffList) {
            if (currentStaff instanceof AdminStaff && adminID.equals(currentStaff.getStaffID())) {
                TransportSystem.getInstance().setCurrentAdmin((AdminStaff) currentStaff);
                dispose();
                MainMenu tempMenu;
                tempMenu = new MainMenu();
                tempMenu.setVisible(true);
                return;

            }
        }
        JOptionPane.showMessageDialog(this, "This Admin does not exist!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAdminID = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter AdminID: ");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnLogin)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnLogin)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        findAdmin();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAdminID;
    // End of variables declaration//GEN-END:variables
}
