package forms;


import java.awt.Window;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mainClasses.TransportSystem;
import utilities.IObserver;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Liam
 */
public class MainMenu extends javax.swing.JFrame implements IObserver {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        TransportSystem.getInstance().registerObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRentVehicle = new javax.swing.JButton();
        btnVehicleReports = new javax.swing.JButton();
        btnUpdateVehicle = new javax.swing.JButton();
        btnAddService = new javax.swing.JButton();
        btnReturnVehicle = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAddVehicle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRentVehicle.setText("Rent Vehicle");
        btnRentVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentVehicleActionPerformed(evt);
            }
        });

        btnVehicleReports.setText("Vehicle Reports");

        btnUpdateVehicle.setText("Update Vehicle");
        btnUpdateVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVehicleActionPerformed(evt);
            }
        });

        btnAddService.setText("Add Service");

        btnReturnVehicle.setText("Return Vehicle");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAddVehicle.setText("Add Vehicle");
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRentVehicle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReturnVehicle))
                    .addComponent(btnVehicleReports)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdateVehicle)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddVehicle))
                    .addComponent(btnAddService))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRentVehicle)
                    .addComponent(btnReturnVehicle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVehicleReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateVehicle)
                    .addComponent(btnAddVehicle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddService)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentVehicleActionPerformed
        //for (Window test : RentCar.getWindows())
        //{
            //if(test.class == RentCar())
            //{
                
            //}
            //test.dispose();
        //}
        
        RentCar rc = new RentCar();
        rc.setVisible(true);
    }//GEN-LAST:event_btnRentVehicleActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        Login tempLogin;
       tempLogin = new Login();
       tempLogin.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
        AddVehicle tempAddVehicle;
        tempAddVehicle = new AddVehicle();
        tempAddVehicle.setVisible(true);
    }//GEN-LAST:event_btnAddVehicleActionPerformed

    private void btnUpdateVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVehicleActionPerformed
        UpdateVehicle tempUpdateVehicle;
        tempUpdateVehicle = new UpdateVehicle();
        tempUpdateVehicle.setVisible(true);
    }//GEN-LAST:event_btnUpdateVehicleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRentVehicle;
    private javax.swing.JButton btnReturnVehicle;
    private javax.swing.JButton btnUpdateVehicle;
    private javax.swing.JButton btnVehicleReports;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        
        /*JFileChooser objFileDialogue = new JFileChooser();
        int intDialogResult = JFileChooser.CANCEL_OPTION;
        intDialogResult = objFileDialogue.showSaveDialog(this);
        if (intDialogResult == JFileChooser.APPROVE_OPTION)
        {
            File objFile = objFileDialogue.getSelectedFile(); */
            File objFile = new File("System");  
            try (ObjectOutputStream objOut = new ObjectOutputStream(
                            new BufferedOutputStream(
                            new FileOutputStream(objFile))))
            {
                //Write the warehouse object (stockList) to the file
                objOut.writeObject(TransportSystem.getInstance());
                JOptionPane.showMessageDialog(this,
                        "Transport System data saved.",
                        "Save completed.", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex)
            {              
                JOptionPane.showMessageDialog(this,
                        "Error saving data model.",
                        "File save error: " + ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
        /*} else
        {
            JOptionPane.showMessageDialog(this,
                    "Save operation cancelled",
                    "Operation aborted", JOptionPane.ERROR_MESSAGE);
        }*/
    }
}
