/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import mainClasses.TransportSystem;
import mainClasses.Vehicle;

/**
 *
 * @author Shivers
 */
public class UpdateVehicle extends javax.swing.JFrame {

    /**
     * Creates new form UpdateVehicle
     */
    ArrayList<Vehicle> vehicles;
    Vehicle selectedVehicle;

    public UpdateVehicle() {
        initComponents();
        DefaultListModel<String> model = new DefaultListModel<>();
        vehicles = TransportSystem.getInstance().getVehicleList();
        for (Vehicle tempVehicle : vehicles) {
            model.addElement(tempVehicle.getLicensePlate());
        }
        lstVehicleList.setModel(model);
        if (model.isEmpty() == false) {
            lstVehicleList.setSelectedIndex(0);
            changeVehicle();
        }

        lstVehicleList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                changeVehicle();
            }
        });
    }

    private void saveChanges() {
        selectedVehicle = vehicles.get(lstVehicleList.getSelectedIndex());
        Boolean available, damaged, forSale;
        available = rbtAvailable.isSelected();
        damaged = rbtDamaged.isSelected();
        forSale = rbtForSale.isSelected();
        if (available != selectedVehicle.isAvailable() || forSale != selectedVehicle.isForSale() || damaged != selectedVehicle.isDamaged()) {
            selectedVehicle.setAllStates(available, forSale, damaged);
        }
    }

    private void changeVehicle() {
        ArrayList<Vehicle> vehicles = TransportSystem.getInstance().getVehicleList();

        selectedVehicle = vehicles.get(lstVehicleList.getSelectedIndex());
        if (selectedVehicle.isForSale() == true) {
            rbtForSale.setSelected(true);
        } else {
            rbtNotForSale.setSelected(true);
        }
        if (selectedVehicle.isDamaged() == true) {
            rbtDamaged.setSelected(true);
        } else {
            rbtNotDamaged.setSelected(true);
        }
        if (selectedVehicle.isAvailable() == true && selectedVehicle.isDamaged() == false && selectedVehicle.isForSale() == false) {
            rbtAvailable.setSelected(true);
            rbtAvailable.setEnabled(true);
        } else if (selectedVehicle.isAvailable() == false && selectedVehicle.isDamaged() == false && selectedVehicle.isForSale() == false) {
            rbtUnavailable.setSelected(true);
            rbtAvailable.setEnabled(true);

        } else {
            rbtUnavailable.setSelected(true);
            rbtAvailable.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availability = new javax.swing.ButtonGroup();
        forSale = new javax.swing.ButtonGroup();
        damaged = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVehicleList = new javax.swing.JList<>();
        lblAvailableCars = new javax.swing.JLabel();
        rbtAvailable = new javax.swing.JRadioButton();
        rbtUnavailable = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rbtNotForSale = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbtForSale = new javax.swing.JRadioButton();
        rbtNotDamaged = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtDamaged = new javax.swing.JRadioButton();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstVehicleList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstVehicleList);

        lblAvailableCars.setText("Cars:");

        availability.add(rbtAvailable);
        rbtAvailable.setText("Available");

        availability.add(rbtUnavailable);
        rbtUnavailable.setText("Unavailable");

        jLabel1.setText("Availability:");

        forSale.add(rbtNotForSale);
        rbtNotForSale.setText("Not For Sale");
        rbtNotForSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNotForSaleActionPerformed(evt);
            }
        });

        jLabel2.setText("For Sale:");

        forSale.add(rbtForSale);
        rbtForSale.setText("For Sale");
        rbtForSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtForSaleActionPerformed(evt);
            }
        });

        damaged.add(rbtNotDamaged);
        rbtNotDamaged.setText("Not Damaged");
        rbtNotDamaged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNotDamagedActionPerformed(evt);
            }
        });

        jLabel3.setText("Damaged:");

        damaged.add(rbtDamaged);
        rbtDamaged.setText("Damaged");
        rbtDamaged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDamagedActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSave.setText("Save Changes");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAvailableCars)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtUnavailable)
                                    .addComponent(rbtAvailable)
                                    .addComponent(jLabel1))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtNotForSale)
                                    .addComponent(rbtForSale)
                                    .addComponent(jLabel2))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtNotDamaged)
                                    .addComponent(rbtDamaged)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClose)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtDamaged)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtNotDamaged))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvailableCars)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtAvailable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtUnavailable))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtForSale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtNotForSale)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveChanges();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void rbtForSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtForSaleActionPerformed
        rbtUnavailable.setSelected(true);
        rbtAvailable.setEnabled(false);
    }//GEN-LAST:event_rbtForSaleActionPerformed

    private void rbtDamagedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDamagedActionPerformed
        rbtUnavailable.setSelected(true);
        rbtAvailable.setEnabled(false);
    }//GEN-LAST:event_rbtDamagedActionPerformed

    private void rbtNotDamagedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNotDamagedActionPerformed
        if (rbtDamaged.isSelected() != true && rbtForSale.isSelected() != true) {
            rbtAvailable.setEnabled(true);
        }
    }//GEN-LAST:event_rbtNotDamagedActionPerformed

    private void rbtNotForSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNotForSaleActionPerformed
        if (rbtDamaged.isSelected() != true && rbtForSale.isSelected() != true) {
            rbtAvailable.setEnabled(true);
        }
    }//GEN-LAST:event_rbtNotForSaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup availability;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup damaged;
    private javax.swing.ButtonGroup forSale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailableCars;
    private javax.swing.JList<String> lstVehicleList;
    private javax.swing.JRadioButton rbtAvailable;
    private javax.swing.JRadioButton rbtDamaged;
    private javax.swing.JRadioButton rbtForSale;
    private javax.swing.JRadioButton rbtNotDamaged;
    private javax.swing.JRadioButton rbtNotForSale;
    private javax.swing.JRadioButton rbtUnavailable;
    // End of variables declaration//GEN-END:variables
}
