
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import mainClasses.AdminStaff;
import mainClasses.CarPark;
import mainClasses.Staff;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Liam
 */
public class LogIn extends javax.swing.JFrame {

        
    private void loadCarParkData() throws IOException
    {
        CarPark.getInstance();
        //Create Dialog
        JFileChooser objFileDialogue = new JFileChooser();
        //Create Dialogue result with default cancel action
        int intDialogResult = JFileChooser.CANCEL_OPTION;
        //Show Dialog
        intDialogResult = objFileDialogue.showOpenDialog(this);
        if (intDialogResult == JFileChooser.APPROVE_OPTION)
        {
            //Get the file name to use from the dialog
            File objFile = objFileDialogue.getSelectedFile();
            //Check the file exists and is readable
            if(objFile.exists() && objFile.canRead())
            {
                //Try to read the file and create new data model
                try(ObjectInputStream objIn = new ObjectInputStream(
                        new BufferedInputStream(
                        new FileInputStream(objFile))))
                {
                    Object objData = objIn.readObject();
                    //We know that this should be a CarPark object try to cast it to a CarPark
                    CarPark.setCarPark((CarPark)objData);
                    //If we have a CarPark object...                    
                }
                catch(ClassNotFoundException | IOException | ClassCastException ex)
                {
                    JOptionPane.showMessageDialog(this, 
                            "Data file could not be read", 
                            "Operation aborted", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, 
                        "File not found / unreadable.", 
                        "Error accessing file", JOptionPane.ERROR_MESSAGE);
            }
        } else
        {
            JOptionPane.showMessageDialog(this, 
                    "File load cancelled", 
                    "Operation aborted", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * Creates new form MainMenu
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAdminID = new javax.swing.JTextField();
        btnConfirmID = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblLogInResult = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConfirmID.setText("Confirm");
        btnConfirmID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmIDActionPerformed(evt);
            }
        });

        lblID.setText("ID:");

        lblLogInResult.setText("Something");

        testList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(testList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmID))
                    .addComponent(lblLogInResult))
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmID)
                            .addComponent(lblID))
                        .addGap(18, 18, 18)
                        .addComponent(lblLogInResult))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmIDActionPerformed
        
        ArrayList<Staff> staffList = CarPark.getStaffList();
        
        testList.removeAll();
        
        for(Staff tempStaff : staffList)
        {
            System.out.println(tempStaff.getFirstName());
            
            
            /*
            if (tempStaff.getClass() == AdminStaff.Class)
            {
                this.dispose();
                new MainMenu().setVisible(true);
            }
            */
        }
        
    }//GEN-LAST:event_btnConfirmIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLogInResult;
    private javax.swing.JList<String> testList;
    private javax.swing.JTextField txtAdminID;
    // End of variables declaration//GEN-END:variables
}
